language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
  - "iojs-v3.2.0"
addons:
  code_climate:
    repo_token: a08a366ae3dedbc8bb6fe8ba2b2c0cae4eef2b966091abbe23fdb66dd56b3b88
script: "npm run coverage"
after_script:
  - codeclimate-test-reporter < etc/lcov.info
